# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f84a6322a89afa6b4222304ef4731b9087645b1f1099b3a7cc79c9c4c4b2738b5b021ff2aa07e1fa810afe9bae051e9b855ab593651816db9a47c180e901f177

test:
  secret_key_base: 197b3e92786b86d0c76e5003e7d34515f8865f1803d3830e178eea288226d773fd232edf8b4fc6fd7cac1cc7dd618aa2d732d719baecbc686f4e1323555e75a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
